# application-local.yml

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


jwt:
  secret: u8P5aLk2q9fD1h7X3mB0rV6sW4yJ8nZ1Q2tC5eH7fG9=

  expiration: 3600000 # 1 hour

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG

server:
  port: 8080
